### ISSUE TITLE
Error in cond.density.estimation

### ISSUE THREAD

**Issue by jkteske** [Bo-Ning/Predicting-exoplanet-mass-and-radius-relationship#1]
I get the following error upon sourcing the code in R.Studio:

Error in cond.density.estimation(y = radius.sample[i], y.max = Radius.max,  : 
  could not find function "cond.density.estimation"

I am a complete novice in R so I don't know if this will affect the results or not. Please advise!

**Comment by shbhuk** [comment]
Hi Johanna, there are some bugs in the code that are not ironed out. I can work on ironing some of them out and pushing a fix. But for now, if you prefer we do have a Python version - 

http://adsabs.harvard.edu/abs/2019arXiv190300042K
https://github.com/shbhuk/mrexo

**Comment by yc-ning** [comment]
This is caused by I changed the name "cond.density.estimation" to "conditional.estimation", but did not change its name when I use this function. I have fixed this bug in "MRpredict.R". I do not think this will affect the results.

**Comment by jkteske** [comment]
FYI, I think there is still an issue, or I am doing something wrong. I get the following results:

WITHOUT ERROR DEFINED
Rp | Median Mass | 16th Percentile Mass | 84th Percentile Mass
2.578031 | 6.308677111 | 3.048778689 | 13.05142704

WITH ERROR DEFINED
Rp error | Median Mass | 16th Percentile Mass | 84th Percentile Mass
0.637317 | 16.15317879 | 3.072425776 | 190.7343879

With the python version of the code, I get much more similar results without and with the error defined.

**Comment by shbhuk** [comment]
Hi Johanna,
These are the results from MRExo - 

The first number is the median mass, then the 16,84% quantile, and the last one is the mass of an iron planet with given radius. 

```
predict_from_measurement(measurement=2.578031)
Out[2]: [5.704233682297099, array([ 1.37277019, 18.24992319]), 275.0849064276575]

predict_from_measurement(measurement=2.578031, measurement_sigma=0.637317)
Out[3]: [5.047464863737498, array([ 1.03025368, 17.34137646]), 275.0849064276575]
```

Keep in mind, that the default MRExo results are for the 24 planet M dwarf sample. 
To switch to Kepler results - 
```

predict_from_measurement(measurement=2.578031, dataset='kepler')
Out[4]: [6.513540354151802, array([ 2.74781546, 15.56352158]), 275.0849064276575]

predict_from_measurement(measurement=2.578031, measurement_sigma=0.637317, dataset='kepler')
Out[5]: [6.233833375518444, array([ 2.59258261, 15.1325232 ]), 275.0849064276575]
```

The R code by default uses the Kepler sample. That being said, the R code result does seem suspicious. Maybe check if both of your input parameters are in linear or log units?
 
You can email me if you have any issues with the Python code.
